spring.application.name=interviewer-backend

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/interviewer_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Execute schema.sql on startup
spring.sql.init.mode=always
